# Generated by Django 2.0.5 on 2018-07-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_time', models.CharField(blank=True, max_length=100, null=True)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_money', models.CharField(blank=True, max_length=100, null=True)),
                ('job_meanmoney', models.CharField(blank=True, db_column='job_meanMoney', max_length=100, null=True)),
                ('job_address', models.CharField(blank=True, max_length=100, null=True)),
                ('job_jy', models.CharField(blank=True, max_length=100, null=True)),
                ('job_xl', models.CharField(blank=True, max_length=100, null=True)),
                ('job_hrname', models.CharField(blank=True, db_column='job_hrName', max_length=100, null=True)),
                ('job_hrleader', models.CharField(blank=True, max_length=100, null=True)),
                ('job_zwtext', models.TextField(blank=True, null=True)),
                ('job_tdtext', models.TextField(blank=True, null=True)),
                ('job_gstext', models.TextField(blank=True, null=True)),
                ('job_comname', models.CharField(blank=True, db_column='job_comName', max_length=100, null=True)),
                ('company_username', models.CharField(blank=True, db_column='company_userName', max_length=100, null=True)),
                ('company_money', models.CharField(blank=True, max_length=100, null=True)),
                ('company_time', models.CharField(blank=True, max_length=100, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('company_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'job_msg',
                'managed': False,
            },
        ),
    ]
