# Generated by Django 2.0.5 on 2018-07-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='电话')),
                ('image', models.ImageField(null=True, upload_to='user/images', verbose_name='头像')),
                ('state', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户列表',
            },
        ),
    ]
