# Generated by Django 2.0.5 on 2018-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=100, verbose_name='token'),
            preserve_default=False,
        ),
    ]
